#!/bin/bash

if [[ "$1" == "" ]]
   then
   echo "Usage: create-repo NAME"
   echo "This is *not* for repository mirrors"
   exit 1
fi

. git-funcs
check_not_root

NAME=$1
if [[ "${NAME: -4}" == ".git" ]]
    then
    echo "Error: Provide the repository name without '.git' on the end."
    exit 1
fi

GIT_DIR=/srv/git/$NAME.git
mkdir -p $GIT_DIR

GIT_DIR=$GIT_DIR git init --shared=0664

cd $GIT_DIR
# Default hooks
rm -rf hooks
ln -s /srv/git/scripts/hooks hooks

sort_config
