#!/bin/bash

. git-funcs
check_not_root

cd /srv/git
find -name '*.git' -type d  | sort | 
grep -v 'scripts/.git' |
while read repodir
do
    reponame=`echo $repodir | sed -e 's#^\./##'`
    repodesc=`cat $repodir/description`

    echo $reponame: $repodesc
done > /srv/git/repolist

