#!/bin/bash

# CIAbot munging:
reponame=`pwd | sed -e 's#/srv/git/##' | sed -e 's#\.git$##'`
refname=$reponame

oldhead=$2
newhead=$3
for merged in $(git rev-list $newhead ^$oldhead | tac); do
        /srv/git/scripts/hooks/ciabot.pl $merged $refname               
        if test $? = 110; then
                echo "CIA.vc timed out; bees"
                exit 0
        fi
done                                         

echo `date +%s` $USER `pwd` $oldhead $newhead >> /srv/git/push-log

